# Generated by Django 3.2.1 on 2021-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dec', models.TextField()),
                ('Images', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
