# Generated by Django 3.2.1 on 2021-05-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dec_name', models.CharField(max_length=100)),
                ('dec', models.TextField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
