# Generated by Django 3.2.1 on 2021-05-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_acheivements'),
    ]

    operations = [
        migrations.CreateModel(
            name='certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dec', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('Images', models.ImageField(upload_to='pics')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
